### ISSUE TITLE
Regression on Datastax 3.0.0 driver

### ISSUE THREAD

**Issue by jalkanen** [paradoxical-io/cassandra-loader#3]
Looks like the use of getDate() is incorrect for timestamp columns as per http://www.datastax.com/dev/blog/datastax-java-driver-3-0-0-released#compatibility-with-cassandra-3.0.  It should really be getTimestamp().

```
Exception in thread "main" com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [timestamp <-> com.datastax.driver.core.LocalDate]
    at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:679)
    at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:526)
    at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:506)
    at com.datastax.driver.core.CodecRegistry.access$200(CodecRegistry.java:140)
    at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:211)
    at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:208)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at com.datastax.driver.core.CodecRegistry.lookupCodec(CodecRegistry.java:480)
    at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:448)
    at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:430)
    at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:69)
    at com.datastax.driver.core.AbstractGettableByIndexData.getDate(AbstractGettableByIndexData.java:174)
    at com.datastax.driver.core.AbstractGettableData.getDate(AbstractGettableData.java:26)
    at com.datastax.driver.core.AbstractGettableData.getDate(AbstractGettableData.java:111)
    at io.paradoxical.cassandra.loader.DbScriptsRunner.lambda$getLatestDBVersion$0(DbScriptsRunner.java:162)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
    at java.util.TimSort.sort(TimSort.java:220)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at io.paradoxical.cassandra.loader.DbScriptsRunner.getLatestDBVersion(DbScriptsRunner.java:168)
    at io.paradoxical.cassandra.loader.DbScriptsRunner.run(DbScriptsRunner.java:66)
    at io.paradoxical.cassandra.loader.DbScriptsRunner.run(DbScriptsRunner.java:37)
    at io.paradoxical.cassandra.loader.Main.main(Main.java:40)

```

My db_version currently looks like this:

```
cqlsh:keyspace> select * from db_version;

 version | updated_date
---------+--------------------------
       1 | 2016-04-15 16:36:21+0000
       2 | 2016-04-20 11:34:26+0000

(2 rows)
```

**Comment by devshorts** [comment]
Nice catch!
